# Generated by Django 5.2.6 on 2025-11-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('hámster', 'Hámster'), ('conejo', 'Conejo'), ('pajaro', 'Pájaro'), ('otro', 'Otro')], max_length=20)),
                ('años', models.PositiveIntegerField()),
                ('caracter', models.CharField(choices=[('tranquilo', 'Tranquilo'), ('jugueton', 'Juguetón'), ('agresivo', 'Agresivo'), ('timido', 'Tímido'), ('otro', 'Otro')], max_length=20)),
                ('foto', models.ImageField(upload_to='mascotas/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
